#!/usr/bin/env python3
"""
Script to convert Roboto TTF fonts to base64 for jsPDF
Usage: python scripts/convert-font.py
"""

import os
import base64
import sys

# Paths
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(script_dir)

roboto_regular_path = os.path.join(project_root, 'src', 'lib', 'Roboto', 'static', 'Roboto-Regular.ttf')
roboto_bold_path = os.path.join(project_root, 'src', 'lib', 'Roboto', 'static', 'Roboto-Bold.ttf')
output_normal_path = os.path.join(project_root, 'src', 'lib', 'fonts', 'roboto-normal.ts')
output_bold_path = os.path.join(project_root, 'src', 'lib', 'fonts', 'roboto-bold.ts')

def convert_font_to_base64(font_path):
    """Convert TTF font file to base64 string"""
    try:
        if not os.path.exists(font_path):
            print(f"❌ Font file not found: {font_path}")
            return None
        
        with open(font_path, 'rb') as f:
            font_bytes = f.read()
            base64_string = base64.b64encode(font_bytes).decode('utf-8')
            return base64_string
    except Exception as e:
        print(f"❌ Error converting font {font_path}: {e}")
        return None

def update_font_file(output_path, font_name, base64_string, is_bold=False):
    """Update TypeScript font file with base64 string"""
    if not base64_string:
        print(f"❌ No base64 string provided for {font_name}")
        return False

    const_name = 'RobotoBold' if is_bold else 'RobotoNormal'
    
    file_content = f'''/**
 * {font_name} font in base64 format for jsPDF
 * 
 * This file is auto-generated by scripts/convert-font.py
 * DO NOT EDIT MANUALLY - Run the script to regenerate
 * 
 * Font source: src/lib/Roboto/static/{font_name}
 */

export const {const_name} = '{base64_string}';
'''

    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(file_content)
        size_kb = len(base64_string) / 1024
        print(f"✅ Successfully updated {output_path}")
        print(f"   Font size: {size_kb:.2f} KB (base64)")
        return True
    except Exception as e:
        print(f"❌ Error writing file {output_path}: {e}")
        return False

# Main execution
print('🔄 Converting Roboto fonts to base64...\n')

# Convert Roboto Regular
print('📝 Converting Roboto-Regular.ttf...')
regular_base64 = convert_font_to_base64(roboto_regular_path)
if regular_base64:
    update_font_file(output_normal_path, 'Roboto-Regular.ttf', regular_base64, False)
else:
    print('❌ Failed to convert Roboto-Regular.ttf')

print()

# Convert Roboto Bold
print('📝 Converting Roboto-Bold.ttf...')
bold_base64 = convert_font_to_base64(roboto_bold_path)
if bold_base64:
    update_font_file(output_bold_path, 'Roboto-Bold.ttf', bold_base64, True)
else:
    print('❌ Failed to convert Roboto-Bold.ttf')

print('\n✨ Font conversion complete!')
print('📌 Next steps:')
print('   1. Restart your development server')
print('   2. Try exporting a PDF - Vietnamese fonts should now work correctly!')
